/**
 * Seed all Zambian health facilities into Firebase RTDB.
 * Run with: node scripts/seed_facilities.js
 *
 * Requires Node 18+ (uses built-in fetch) or install node-fetch v2:
 *   npm install node-fetch@2
 * and add: const fetch = require('node-fetch');
 */

const FIREBASE_URL = 'https://chimwemwe-app-default-rtdb.firebaseio.com/facilities.json';

const RAW = `ANTHU OMWE AMBULANCE	Central	Chibombo
ANTHU OMWE HEALTH CENTRE	Central	Chibombo
ATHALIAH HEALTH CARE	Central	Chibombo
BETHEL MEDICAL CLINIC- 10 MILE	Central	Chibombo
CARE MARK MEDICAL CENTRE	Central	Chibombo
CHAMAKUBI HEALTH POST	Central	Chibombo
CHIBOMBO RURAL HEALTH CENTRE	Central	Chibombo
CHIKOBO RURAL HEALTH CENTRE	Central	Chibombo
CHIKUMBI ZNS HEALTH POST	Central	Chibombo
CHILOCHABALENJE HEALTH POST	Central	Chibombo
CHIPESO RURAL HEALTH CENTRE	Central	Chibombo
CHITANDA LUMAMBA ADVENTIST HOSPITAL	Central	Chibombo
CHITANDA RURAL HEALTH CENTRE	Central	Chibombo
GOLDEN VALLEY RURAL HEALTH CENTRE	Central	Chibombo
HARPER ANN RURAL HEALTH CENTRE	Central	Chibombo
HOPE IN CHRIST - CHIBOMBO	Central	Chibombo
IK CHARITABLE TRUST CLINIC	Central	Chibombo
IPONGO RURAL HEALTH CENTRE	Central	Chibombo
ITUMBWE HEALTH POST	Central	Chibombo
KABANGALALA RURAL HEALTH CENTRE	Central	Chibombo
KAMAILA HEALTH POST	Central	Chibombo
KANWANJIBA HEALTH POST	Central	Chibombo
KAPARU RURAL HEALTH CENTRE	Central	Chibombo
KAPILA HEALTH POST	Central	Chibombo
KAPOPO HEALTH POST	Central	Chibombo
KAYOSHA RURAL HEALTH CENTRE	Central	Chibombo
KEEMBE RURAL HEALTH CENTRE	Central	Chibombo
KELAK MEDICAL CENTRE	Central	Chibombo
LONE STAR MEDICAL CLINIC	Central	Chibombo
MAKOKA RURAL HEALTH CENTRE	Central	Chibombo
MALAMBANYAMA RURAL HEALTH CENTRE	Central	Chibombo
MALUNDU HEALTH POST	Central	Chibombo
MAYOTA HEALTH POST	Central	Chibombo
MBOSHYA RURAL HEALTH CENTRE	Central	Chibombo
MUKALASHI	Central	Chibombo
MUKASHICHIMBWE HEALTH POST	Central	Chibombo
MULONDA HEALTH POST	Central	Chibombo
MULULU HEALTH POST	Central	Chibombo
MUNGULE MINI HOSPITAL	Central	Chibombo
MUNGULE RURAL HEALTH CENTRE	Central	Chibombo
MUNTEMBA RURAL HEALTH CENTRE	Central	Chibombo
MUSOPELO HEALTH POST	Central	Chibombo
MWACHISOMPOLA FIRST LEVEL HOSPITAL	Central	Chibombo
MWACHISOMPOLA RURAL HEALTH CENTRE	Central	Chibombo
MWANJUNI HEALTH POST	Central	Chibombo
MWELEBI HEALTH POST	Central	Chibombo
MZAMANE HEALTH CENTRE	Central	Chibombo
NALUYANDA RURAL HEALTH CENTRE	Central	Chibombo
NAMAYANI HEALTH POST	Central	Chibombo
NAMUNUNGA HEALTH POST	Central	Chibombo
NTAPWILA HEALTH POST	Central	Chibombo
PETRA MEDICAL CENTRE	Central	Chibombo
SHIFWANKULA HEALTH POST	Central	Chibombo
SHIMUKUNI RURAL HEALTH CENTRE	Central	Chibombo
SOUTH POINT HOSPITAL- CHIBOMBO	Central	Chibombo
SR LUCY O'BRIEN MEMORIAL RHC	Central	Chibombo
ST. THOMAS 1ST LEVEL HOSPITAL	Central	Chibombo
TWALUMBA RURAL HEALTH CENTRE	Central	Chibombo
ZNS CHISAMBA RURAL HEALTH CENTRE	Central	Chibombo
BETHEL MEDICAL CLINIC- FLINGILA	Central	Chisamba
BOMBWE HEALTH POST	Central	Chisamba
CHIKONKOMENE HEALTH POST	Central	Chisamba
CHIPEMBI MISSION RURAL HEALTH CENTRE	Central	Chisamba
CHISAMBA RANCH HEALTH POST	Central	Chisamba
CHISAMBA RURAL HEALTH CENTRE	Central	Chisamba
KACHELE HEALTH POST	Central	Chisamba
KANAKANTAPA RURAL HEALTH CENTRE	Central	Chisamba
KAPUTI RURAL HEALTH POST	Central	Chisamba
KASOSOLO HEALTH POST	Central	Chisamba
KAWAMA HEALTH POST	Central	Chisamba
LIFWAMBULA RURAL HEALTH CENTRE	Central	Chisamba
LITETA HOSPITAL	Central	Chisamba
LITETA HOSPITAL AFFILIATED HEALTH CENTRE	Central	Chisamba
MAKENI RURAL HEALTH POST	Central	Chisamba
MALOMBE RURAL HEALTH CENTRE	Central	Chisamba
MOMBOSHI HEALTH POST	Central	Chisamba
MULUNGUSHI AGRO RURAL HEALTH CENTRE	Central	Chisamba
MUPAMAPAMO RURAL HEALTH POST	Central	Chisamba
MUSWISHI RURAL HEALTH CENTRE	Central	Chisamba
MWANTAYA HEALTH POST	Central	Chisamba
MWAPULA HEALTH POST	Central	Chisamba
CHALILO RURAL HEALTH CENTER	Central	Chitambo
CHIPUNDU RURAL HEALTH CENTER	Central	Chitambo
CHITAMBO DISTRICT HOSPITAL	Central	Chitambo
CHITAMBO HOSPITAL AFFILIATED HEALTH CENTER	Central	Chitambo
GIBSON RURAL HEALTH CENTER	Central	Chitambo
KAFINDA HEALTH POST	Central	Chitambo
KATIKULULA HEALTH POST	Central	Chitambo
KATIKULULA MINI HOSPITAL	Central	Chitambo
KATONGA HEALTH POST	Central	Chitambo
MAPEPALA RURAL HEALTH CENTRE	Central	Chitambo
MATEYO KAKUMBI HEALTH POST	Central	Chitambo
MPELEMBE RURAL HEALTH CENTER	Central	Chitambo
MUCHINKA RURAL HEALTH CENTER	Central	Chitambo
MUKANDO RURAL HEALTH POST	Central	Chitambo
MULAUSHI HEALTH POST	Central	Chitambo
MWIMBULA MINI HOSPITAL	Central	Chitambo
NAKATAMBO HEALTH POST	Central	Chitambo
REUBEN HEALTH POST	Central	Chitambo
YORUM MWANJE RHC	Central	Chitambo
89A INDEPENDENCE WAY SURGERY	Central	Kabwe
BLOSSOM SURGERY	Central	Kabwe
BRUNELI HEALTH POST	Central	Kabwe
BWACHA URBAN HEALTH CENTRE	Central	Kabwe
CHANKALAMU HEALTH POST	Central	Kabwe
CHILILALILA HEALTH POST	Central	Kabwe
CHINDWIN CAMP HOSPITAL	Central	Kabwe
CHITAKATA A HEALTH POST	Central	Kabwe
CHITAKATA B HEALTH POST	Central	Kabwe
CHOWA FOREST HEALTH POST	Central	Kabwe
CHOWA URBAN HEALTH CENTRE	Central	Kabwe
CHRESO MINISTRIES KABWE CLINIC	Central	Kabwe
EYE-CO OPTICIAN- KABWE	Central	Kabwe
HAMUDUDU HEALTH POST	Central	Kabwe
HUMKEL MEDICAL CENTRE	Central	Kabwe
JEABI HEALTH CLINIC	Central	Kabwe
KABWE CENTRAL HOSPITAL	Central	Kabwe
KABWE TRUST CLINIC	Central	Kabwe
KABWE WOMEN NEWBORN CHILDREN HOSPITAL	Central	Kabwe
KAFULAMASE HEALTH POST	Central	Kabwe
KALIMA HEALTH POST	Central	Kabwe
KALWELWE HEALTH CENTRE	Central	Kabwe
KAMAKUTI HEALTH POST	Central	Kabwe
KANGOMBA HEALTH POST	Central	Kabwe
KASANDA URBAN HEALTH CENTRE	Central	Kabwe
KASAVASA RURAL HEALTH CENTRE	Central	Kabwe
KATONDO MINI HOSPITAL	Central	Kabwe
KATONDO URBAN HEALTH CENTRE	Central	Kabwe
KAWAMA URBAN HC (KABWE)	Central	Kabwe
KOHIMA CAMP HOSPITAL	Central	Kabwe
LOT40 HEALTH POST	Central	Kabwe
MAGANDANYAMA HEALTH POST	Central	Kabwe
MAHATMA GHANDHI MEMORIAL URBAN HEALTH CENTRE	Central	Kabwe
MAKULULU MINI HOSPITAL	Central	Kabwe
MAKULULU URBAN HEALTH CENTRE	Central	Kabwe
MAKUPU A HEALTH POST	Central	Kabwe
MAKUPU B HEALTH POST	Central	Kabwe
MELA MEDICAL CENTRE	Central	Kabwe
METROPOLIS LAB - KABWE	Central	Kabwe
MPIMA DAIRY RURAL HEALTH CENTRE	Central	Kabwe
MPIMA PRISON CLINIC	Central	Kabwe
MUKOBEKO MAXIMUM PRISON HEALTH POST	Central	Kabwe
MUKOBEKO MEDIUM HEALTH CENTRE	Central	Kabwe
MUKOBEKO TOWNSHIP URBAN HEALTH CENTRE	Central	Kabwe
MUKUNI INSURANCE CLINIC	Central	Kabwe
MUKUNI MEDICAL CENTRE- LUKANGA	Central	Kabwe
MUNGA HEALTH POST	Central	Kabwe
NAKOLI URBAN HEALTH CENTRE	Central	Kabwe
NATUSEKO URBAN HEALTH CENTRE	Central	Kabwe
NGUNGU URBAN HEALTH CENTRE	Central	Kabwe
NKHRUMAH TEACHERS COLLEGE HEALTH POST	Central	Kabwe
NYAMA HEALTH POST	Central	Kabwe
OPTICAL EXPRESS ZAMBIA LIMITED	Central	Kabwe
PATEMOS MEDICAL CENTRE	Central	Kabwe
PHIL OPTICIANS	Central	Kabwe
POLICE URBAN CLINIC- KABWE	Central	Kabwe
POLLEN URBAN HEALTH CENTRE	Central	Kabwe
PROVIDENCE MEDICAL CENTRE	Central	Kabwe
RAILWAY SURGERY URBAN HEALTH CENTRE	Central	Kabwe
RANCHHOD HOSPICE	Central	Kabwe
SUNSHINE DENTAL CLINIC- MUKUYU MALL	Central	Kabwe
UNILABS DIAGNOSTIC & IMAGING CENTRE KABWE	Central	Kabwe
VALLEY VIEW CLINIC- KABWE BRANCH	Central	Kabwe
VALLEY VIEW CLINIC PREMUIM (STRIPES)	Central	Kabwe
VALLEY VIEW DIAGNOSTIC-KABWE	Central	Kabwe
VISION CARE OPTICIANS & EYE CLINIC- KABWE	Central	Kabwe
WAYA HEALTH POST	Central	Kabwe
ZAF KABWE URBAN HEALTH CENTRE	Central	Kabwe
ZNS KABWE URBAN HEALTH CENTRE	Central	Kabwe
CHAMBULUMINA HEALTH POST	Central	Kapirimposhi
CHANKOMO RURAL HEALTH CENTER	Central	Kapirimposhi
CHAPUSHA HEALTH POST	Central	Kapirimposhi
CHAWAMA RURAL HEALTH CENTRE	Central	Kapirimposhi
CHIBWE HEALTH CENTRE	Central	Kapirimposhi
CHILUMBA RURAL HEALTH CENTER	Central	Kapirimposhi
CHIPEPO HEALTH CENTRE	Central	Kapirimposhi
CHISHINKA HEALTH CENTRE	Central	Kapirimposhi
CHITABA RURAL HEALTH CENTRE	Central	Kapirimposhi
HEALTH LIVING MEDICAL CONSULTANCY	Central	Kapirimposhi
ILUNGU HEALTH POST	Central	Kapirimposhi
KABAKA HEALTH POST	Central	Kapirimposhi
KABWALE HEALTH POST	Central	Kapirimposhi
KAFINDA HEALTH POST	Central	Kapirimposhi
KAKULU HEALTH POST	Central	Kapirimposhi
KAMPUMBA RURAL HEALTH CENTRE	Central	Kapirimposhi
KAPANDWE HEALTH POST	Central	Kapirimposhi
KAPIRI MPOSHI DISTRICT HOSPITAL	Central	Kapirimposhi
KAPIRI MPOSHI URBAN HEALTH CENTRE	Central	Kapirimposhi
KASWENDE HEALTH POST	Central	Kapirimposhi
KATO HEALTH POST	Central	Kapirimposhi
KATUKWE HEALTH POST	Central	Kapirimposhi
KAWAMA HEALTH CENTRE	Central	Kapirimposhi
LIKUMBI HEALTH POST	Central	Kapirimposhi
LUANSHIMBA RURAL HEALTH CENTRE	Central	Kapirimposhi
LUKOMBA HEALTH POST	Central	Kapirimposhi
LUNCHU B HEALTH POST	Central	Kapirimposhi
LUNSEMFWA HEALTH CENTRE	Central	Kapirimposhi
MATILYO HEALTH POST	Central	Kapirimposhi
MPUNDE RURAL HEALTH CENTER	Central	Kapirimposhi
MUKONCHI RURAL HEALTH CENTER	Central	Kapirimposhi
MUKUNI INSURANCE CLINIC - KAPIRI	Central	Kapirimposhi
MULUNGUSHI POWER HEALTH POST	Central	Kapirimposhi
MULUNGUSHI UNIVERSITY HEALTH CENTRE	Central	Kapirimposhi
MUTABA RURAL HEALTH CENTRE	Central	Kapirimposhi
NDEKE URBAN HEALTH CENTER	Central	Kapirimposhi
NKOLE RURAL HEALTH CENTRE	Central	Kapirimposhi
RENATO HEALTH POST	Central	Kapirimposhi
S & F PHIRI SURGERY	Central	Kapirimposhi
SHAMPUTA HEALTH POST	Central	Kapirimposhi
ST. PAULS RURAL HEALTH CENTRE	Central	Kapirimposhi
TAZARA HEALTH CENTRE	Central	Kapirimposhi
WAYA RURAL HEALTH CENTRE	Central	Kapirimposhi
BLOSSOM SURGERY MASANSA BRANCH	Central	Luano
BUSA HEALTH POST	Central	Luano
CHEMBE RURAL HEALTH CENTER	Central	Luano
CHIKUPILI RURAL HEALTH CENTER	Central	Luano
CHIMIKA RURAL HEALTH CENTER	Central	Luano
CHINGOMBE MISSION RURAL HEALTH CENTER	Central	Luano
KAMPELEMBE RURAL HEALTH CENTER	Central	Luano
KANYESHA RURAL HEALTH CENTER	Central	Luano
KAUNDULA RURAL HEALTH CENTER	Central	Luano
LITETA HEALTH POST	Central	Luano
LUANO MINI HOSPITAL (MASANSA)	Central	Luano
MAPAPA RURAL HEALTH POST	Central	Luano
MBOROMA RURAL HEALTH CENTER	Central	Luano
MBOSHYA HEALTH CENTRE	Central	Luano
MKUSHI COPPERMINE RURAL HEALTH CENTER	Central	Luano
MULEMBO HEALTH POST	Central	Luano
OLD MKUSHI RURAL HEALTH CENTER	Central	Luano
TAMO HEALTH CENTRE	Central	Luano
TUYU RURAL HEALTH CENTER	Central	Luano
OLIVINE CLINIC	Central	Mksushi
CHALATA RURAL HEALTH CENTRE	Central	Mkushi
CHANGILO HEALTH POST	Central	Mkushi
CHENGELO SCHOOL CLINIC	Central	Mkushi
CHIBEFWE RURAL HEALTH CENTER	Central	Mkushi
CHISANGA RURAL HEALTH CENTER	Central	Mkushi
CHITINA HEALTH POST	Central	Mkushi
FIWILA RURAL HEALTH CENTER	Central	Mkushi
KABENGESHI HEALTH POST	Central	Mkushi
KAKUSHI HEALTH POST	Central	Mkushi
KASALAMAKANGA HEALTH POST	Central	Mkushi
KASOKOTA HEALTH POST	Central	Mkushi
KATUBA HEALTH POST	Central	Mkushi
LESA WESU MEDICAL CENTRE	Central	Mkushi
LILANDA HEALTH POST	Central	Mkushi
MALUBILA HEALTH POST	Central	Mkushi
MATUKU HEALTH POST	Central	Mkushi
MIKUNKU HEALTH CENTER	Central	Mkushi
MILOSO HEALTH POST	Central	Mkushi
MKUSHI DISTRICT HOSPITAL	Central	Mkushi
MOMBOSHI HEALTH POST	Central	Mkushi
MULUNDU HEALTH POST	Central	Mkushi
MULUNGWE RURAL HEALTH CENTRE	Central	Mkushi
MUNSAKAMBA ZNS RURAL HEALTH CENTRE	Central	Mkushi
MUSOFU RURAL HEALTH CENTER	Central	Mkushi
NAMBO HEALTH POST	Central	Mkushi
NKOLONGA FARM CLINIC	Central	Mkushi
NKOLONGA HEALTH POST	Central	Mkushi
NKUMBI RURAL HEALTH CENTER	Central	Mkushi
NSHINSO RURAL HEALTH CENTER	Central	Mkushi
NYENJE HEALTH POST	Central	Mkushi
SHAIBILA HEALTH POST	Central	Mkushi
TAZARA RURAL HEALTH POST	Central	Mkushi
TUSEKELEMO MEDICAL CENTRE	Central	Mkushi
TWATASHA RURAL HEALTH POST	Central	Mkushi
UPPER LUSEMFWA HEALTH POST	Central	Mkushi
UPPER MUSOFU HEALT POST	Central	Mkushi
XOLA MEDICAL CENTRE	Central	Mkushi
ZNS LUANSHIMBA RURAL HEALTH CENTRE	Central	Mkushi
BULUNGU URBAN CLINIC	Central	Mumbwa
CHIWENA RURAL HEALTH CENTRE	Central	Mumbwa
CHUNGA RURAL HEALTH CENTRE	Central	Mumbwa
KABWANGA RURAL HEALTH CENTRE	Central	Mumbwa
KAFWIKAMO HEALTH POST	Central	Mumbwa
KAINDU RURAL HEALTH CENTRE	Central	Mumbwa
KAMILAMBO RURAL HEALTH CENTRE	Central	Mumbwa
KAPEPE HEALTH POST	Central	Mumbwa
KASHINKA HEALTH POST	Central	Mumbwa
KAYUMWEYUMWE HEALTH POST	Central	Mumbwa
KEEZWA RURAL HEALTH CENTRE	Central	Mumbwa
KITUMBA CORRECTIONAL FARM HEALTH POST	Central	Mumbwa
LUBEMBA HEALTH POST	Central	Mumbwa
LUILI RURAL HEALTH CENTRE	Central	Mumbwa
LUNGOBE RURAL HEALTH CENTRE	Central	Mumbwa
LUTALE RURAL HEALTH CENTRE	Central	Mumbwa
MAIMWENE HEALTH POST	Central	Mumbwa
MPUSU RURAL HEALTH CENTER	Central	Mumbwa
MUCHABI RURAL HEALTH CENTRE	Central	Mumbwa
MULUNGUSHI RURAL HEALTH CENTRE	Central	Mumbwa
MUMBWA CORRECTIONAL FACILITY HEALTH POST	Central	Mumbwa
MUMBWA DISTRICT HOSPITAL	Central	Mumbwa
MUMBWA MEDICAL CENTRE	Central	Mumbwa
MYOOYE RURAL HEALTH CENTRE	Central	Mumbwa
NAKANJOLI RURAL HEALTH CENTRE	Central	Mumbwa
NALUBANDA RURAL HEALTH CENTRE	Central	Mumbwa
NALUSANGA HEALTH POST	Central	Mumbwa
NALUVWI HEALTH POST	Central	Mumbwa
NAMABANGA HEALTH POST	Central	Mumbwa
NAMBALA RURAL HEALTH CENTRE	Central	Mumbwa
NANGOMA HOSPITAL AFFILIATED HEALTH CENTRE	Central	Mumbwa
NANGOMA MISSION HOSPITAL	Central	Mumbwa
SHAKUMBILA HEALTH POST	Central	Mumbwa
SHIMBIZHI HEALTH POST	Central	Mumbwa
ZAF MUMBWA RURAL HEALTH CENTRE	Central	Mumbwa
ZNS KALENDA RURAL HEALTH CENTRE	Central	Mumbwa
CHILWA ISLAND RURAL HEALTH CENTER	Central	Ngabwe
MUKUBWE MINI HOSPITAL	Central	Ngabwe
MUKUBWE RURAL HEALTH CENTER	Central	Ngabwe
MUMBACHALA RURAL HEALTH CENTER	Central	Ngabwe
MWINUNA MINI HOSPITAL	Central	Ngabwe
NGABWE MINI HOSPITAL	Central	Ngabwe
NGABWE RURAL HEALTH CENTER	Central	Ngabwe
NSENGWA HEALTH POST	Central	Ngabwe
CHIBALE RURAL HEALTH CENTRE	Central	Serenje
CHIBOBO HEALTH POST	Central	Serenje
CHIBUYESAILI HEALTH POST	Central	Serenje
CHIEF SERENJE HEALTH POST	Central	Serenje
CHIMFUNDE HEALTH POST	Central	Serenje
CHISOMO RURAL HEALTH CENTRE	Central	Serenje
FIKONDO HEALTH POST	Central	Serenje
KABAMBA RURAL HEALTH CENTRE	Central	Serenje
KABANSA HEALTH POST	Central	Serenje
KABUNDI RURAL HEALTH CENTRE	Central	Serenje
KABWE KUPELA HEALTH POST	Central	Serenje
KALELA HEALTH POST	Central	Serenje
KAMENA HEALTH POST	Central	Serenje
KAMPUMBU RURAL HEALTH POST	Central	Serenje
KANONA HEALTH POST	Central	Serenje
KAPESHI HEALTH POST	Central	Serenje
KASEBA HEALTH POST	Central	Serenje
KASHISHI HEALTH POST	Central	Serenje
KOFFI KUNDA HEALTH POST	Central	Serenje
KUNDA LUMWANSHYA HP	Central	Serenje
LUMPAMPA HEALTH POST	Central	Serenje
LUSIWASI HEALTH POST	Central	Serenje
MAILO RURAL HEALTH CENTRE	Central	Serenje
MALCOM MOFFAT COLLEGE HEALTH POST	Central	Serenje
MASASE HEALTH POST	Central	Serenje
MASUNGA HEALTH POST	Central	Serenje
MISWEMA HEALTH POST	Central	Serenje
MPEPETWE (MECCO) RHC	Central	Serenje
MUKOPA HEALTH POST	Central	Serenje
MULILIMA RURAL HEALTH CENTRE	Central	Serenje
MUSAMANI RURAL HEALTH CENTRE	Central	Serenje
NABOBWA HEALTH POST	Central	Serenje
NANSANGA HEALTH POST	Central	Serenje
NCHIMISHI RURAL HEALTH CENTRE	Central	Serenje
NDABALA HEALTH POST	Central	Serenje
OLIVINE MEDICAL CENTRE	Central	Serenje
PEDDY LASHIMA RRDDY (PLR) HP	Central	Serenje
SERENJE DISTRICT HOSPITAL	Central	Serenje
SERENJE HAHC	Central	Serenje
SERENJE URBAN CLINIC	Central	Serenje
SILVER LAND HEALTH POST	Central	Serenje
SOTE HEALTH POST	Central	Serenje
VIEWLINE OPTICIAN	Central	Serenje
ZAMBIA COMPOUND HEALTH POST	Central	Serenje
CHABOTA HEALTH POST	Central	Shibuyunji
KAPYANGA RURAL HEALTH CENTER	Central	Shibuyunji
KAYANGA HEALTH POST	Central	Shibuyunji
MACHILITSO MEDICAL CENTRE	Central	Shibuyunji
MASITEKI HEALTH POST	Central	Shibuyunji
MUKULAIKWA RURAL HEALTH CENTER	Central	Shibuyunji
MUTOMBE HEALTH POST	Central	Shibuyunji
MVUMBE HEALTH POST	Central	Shibuyunji
MWEMBEZHI RURAL HEALTH CENTER	Central	Shibuyunji
NAMPUNDWE MINE CLINIC- KCM	Central	Shibuyunji
NAMPUNDWE RURAL HEALTH CENTER	Central	Shibuyunji
SHABASONJE RURAL HEALTH CENTER	Central	Shibuyunji
SHACELE HEALTH POST	Central	Shibuyunji
SHAMILIMO HEALTH POST	Central	Shibuyunji
SHIKATENDE HEALTH POST	Central	Shibuyunji
SICHOBO RURAL HEALTH CENTER	Central	Shibuyunji
AZATISA CLINIC	Copperbelt	Chililabombwe
CHILILABOMBWE DISTRICT HOSPITAL	Copperbelt	Chililabombwe
CHILILABOMBWE OPTICIANS	Copperbelt	Chililabombwe
CHIMFUNSHI RURAL HEALTH CENTRE	Copperbelt	Chililabombwe
ELI - HIM FAST TRACK CLINIC	Copperbelt	Chililabombwe
ELI - HIM FAST TRACK CLINIC 2	Copperbelt	Chililabombwe
FIKOLONGO HEALTH POST	Copperbelt	Chililabombwe
FITOBAULA HEALTH POST	Copperbelt	Chililabombwe
HEALTH CENTRE NO. 1	Copperbelt	Chililabombwe
HEALTH CENTRE NO. 4	Copperbelt	Chililabombwe
HEALTH CENTRE NO. 5	Copperbelt	Chililabombwe
KAKOSO LEVEL 1 HOSPITAL	Copperbelt	Chililabombwe
KASUMBALESA URBAN HEALTH CENTRE	Copperbelt	Chililabombwe
KAWAMA HEALTH POST (CHILILABOMBWE)	Copperbelt	Chililabombwe
KONKOLA HEALTH POST	Copperbelt	Chililabombwe
KONKOLA MINE HOSPITAL	Copperbelt	Chililabombwe
KONKOLA MINE HOSPITAL AMBULANCE - AGC899ZM	Copperbelt	Chililabombwe
LUAX CLINIC	Copperbelt	Chililabombwe
LUBAMBE MINE AMBULANCE - BAP 4338ZM	Copperbelt	Chililabombwe
LUBAMBE MINE CLINIC	Copperbelt	Chililabombwe
LUBANSA HEALTH POST	Copperbelt	Chililabombwe
LUBENGELE URBAN HEALTH CENTRE	Copperbelt	Chililabombwe
MALUBENI HEALTH POST	Copperbelt	Chililabombwe
MILYASHI EAST HEALTH POST	Copperbelt	Chililabombwe
MITETA HEALTH POST	Copperbelt	Chililabombwe
OCCUPATIONAL HEALTH CLINIC- KCM	Copperbelt	Chililabombwe
PLANTSITE CLINIC NO. 1 SHAFT	Copperbelt	Chililabombwe
PLANTSITE CLINIC NO. 3 SHAFT	Copperbelt	Chililabombwe
PPZ GRACE HEALTH POST	Copperbelt	Chililabombwe
PPZ HEALTH POST	Copperbelt	Chililabombwe
RECSY OPTICAL SOLUTIONS CHILILABOMBWE	Copperbelt	Chililabombwe
SPECIALTY EMERGENCY SERVICES FIRST AID STATION	Copperbelt	Chililabombwe
AFRICAN MEDICARE SERVICES LTD	Copperbelt	Chingola
CHAMAKUBI HEALTH POST	Copperbelt	Chingola
CHAWAMA MINI HOSPITAL	Copperbelt	Chingola
CHIMFUNSHI HEALTH POST	Copperbelt	Chingola
CHINGOLA CORRECTIONAL HEALTH POST	Copperbelt	Chingola
CHINGOLA DENTAL & EYE CLINIC	Copperbelt	Chingola
CHINGOLA MUNICIPAL COUNCIL URBAN HEALTH CENTRE	Copperbelt	Chingola
CHINGOLA SURGERY	Copperbelt	Chingola
CHIWEMPALA URBAN HEALTH CENTRE	Copperbelt	Chingola
FIPUYA HEALTH POST	Copperbelt	Chingola
GOGO OPTICIANS	Copperbelt	Chingola
HEALTH CENTRE 1 (CLINIC ONE)	Copperbelt	Chingola
HEALTH CENTRE 3	Copperbelt	Chingola
IPAFU RURAL HEALTH CENTRE	Copperbelt	Chingola
IVORY DENTAL CLINIC	Copperbelt	Chingola
KABUNDI EAST URBAN HEALTH CENTRE	Copperbelt	Chingola
KALILO RURAL HEALTH CENTRE	Copperbelt	Chingola
KAMUCHANGA HEALTH POST	Copperbelt	Chingola
KASOMPE URBAN HEALTH CENTRE	Copperbelt	Chingola
KATUBA HEALTH POST	Copperbelt	Chingola
KAWAMA HEALTH POST	Copperbelt	Chingola
KINGS HEALTH POST	Copperbelt	Chingola
LUANO KAPISHA HEALTH CENTRE	Copperbelt	Chingola
LULAMBA HEALTH CENTRE	Copperbelt	Chingola
LULAMBA HEALTH POST	Copperbelt	Chingola
LUSHISHI HEALTH POST	Copperbelt	Chingola
MAYO MWICHE MEDICAL IMAGING CENTRE	Copperbelt	Chingola
MAYO MWICHE MOBILE MEDICAL IMAGING CENTRE	Copperbelt	Chingola
MBAYI HEALTH POST	Copperbelt	Chingola
MINE CLINIC- NCHANGA	Copperbelt	Chingola
MUCHINSHI RURAL HEALTH CENTRE	Copperbelt	Chingola
MUSENGA HEALTH POST	Copperbelt	Chingola
MUTENDA RURAL HEALTH CENTRE	Copperbelt	Chingola
NCHANGA 1 URBAN HEALTH CENTRE	Copperbelt	Chingola
NCHANGA HEALTH CENTRE	Copperbelt	Chingola
NCHANGA NORTH GENERAL HOSPITAL	Copperbelt	Chingola
NCHANGA OPEN PIT MINE CLINIC	Copperbelt	Chingola
NCHANGA SOUTH HOSPITAL	Copperbelt	Chingola
NDUNGU HEALTH POST	Copperbelt	Chingola
PHIL (MILANO) OPTICIANS	Copperbelt	Chingola
RECSY OPTICAL SOLUTIONS- CHINGOLA	Copperbelt	Chingola
RUCHNO MEDICAL DIAGNOSTIC CENTRE	Copperbelt	Chingola
SHIMULALA HEALTH POST	Copperbelt	Chingola
SOURCE OF LIFE CLINIC	Copperbelt	Chingola
SOUTHSIDE CLINIQUE	Copperbelt	Chingola
TLP PLANTSITE CLINIC- KCM	Copperbelt	Chingola
ASPIRE CLINIC KALULUSHI BRANCH	Copperbelt	Kalulushi
CHAMBISHI COPPER SMELTER PLANT SITE CLINIC	Copperbelt	Kalulushi
CHAMBISHI GOVERNMENT CLINIC	Copperbelt	Kalulushi
CHAMBISHI MINI HOPSITAL	Copperbelt	Kalulushi
CHAMBISHI TOWNSHIP CLINIC - SINOZAM	Copperbelt	Kalulushi
CHATI RURAL HEALTH CENTRE	Copperbelt	Kalulushi
CHEMBE HEALTH POST	Copperbelt	Kalulushi
CHEMBE NORTH HEALTH POST	Copperbelt	Kalulushi
CHIBOTE HEALTH POST	Copperbelt	Kalulushi
CHIBULUMA MINE AMBULANCE	Copperbelt	Kalulushi
CHIBULUMA MINE PLANT SITE CLINIC	Copperbelt	Kalulushi
CHIBULUMA URBAN HEALTH CENTRE	Copperbelt	Kalulushi
CHISANGWA HEALTH POST	Copperbelt	Kalulushi
CHIWEMBASHI HEALTH POST	Copperbelt	Kalulushi
DENOVAN HEALTH POST	Copperbelt	Kalulushi
EL-ROI MEDICAL CENTRE	Copperbelt	Kalulushi
FITANDA HEALTH POST	Copperbelt	Kalulushi
HEALTHLANE MEDICAL AND DIAGNOSTIC CENTRE	Copperbelt	Kalulushi
HOPE DIAGNOSTIC CENTRE	Copperbelt	Kalulushi
ICHIMPE RURAL HEALTH CENTRE	Copperbelt	Kalulushi
KALENGWA SOUTH HEALTH POST	Copperbelt	Kalulushi
KALULUSHI GENERAL HOSPITAL	Copperbelt	Kalulushi
KALULUSHI GOVERNMENT URBAN HEALTH CENTRE	Copperbelt	Kalulushi
KALULUSHI MAIN URBAN HEALTH CENTRE	Copperbelt	Kalulushi
KALULUSHI TOWNSHIP URBAN HEALTH CENTRE	Copperbelt	Kalulushi
KAMEME HEALTH POST	Copperbelt	Kalulushi
KITE RURAL HEALTH CENTRE	Copperbelt	Kalulushi
LUKOSHI RURAL HEALTH CENTRE	Copperbelt	Kalulushi
LULAMBA HEALTH POST	Copperbelt	Kalulushi
MINDOLO TRAINING FARMS URBAN HEALTH CENTRE	Copperbelt	Kalulushi
MISENGA HEALTH POST	Copperbelt	Kalulushi
MUSAKASHI HEALTH POST	Copperbelt	Kalulushi
SITWE HEALTH POST	Copperbelt	Kalulushi
SOUTH EAST ORE BODY PLANT SITE CLINIC	Copperbelt	Kalulushi
TWAITEKA ZAMBIA COMPOUND HEALTH POST	Copperbelt	Kalulushi
BUCHI MAIN URBAN HEALTH CENTRE	Copperbelt	Kitwe
BUCHI SMALL CHEST URBAN HEALTH CENTRE	Copperbelt	Kitwe
BULANGILILO URBAN HEALTH CENTER	Copperbelt	Kitwe
CAREWELL OASIS MEDICAL SERVICE LTD	Copperbelt	Kitwe
CHAMBOLI GRZ URBAN HEALTH CENTRE	Copperbelt	Kitwe
CHAMBOLI LEVEL 1 HOSPITAL	Copperbelt	Kitwe
CHIMWEMWE LEVEL 1 HOSPITAL	Copperbelt	Kitwe
CHIMWEMWE URBAN CLINIC	Copperbelt	Kitwe
KITWE TEACHING HOSPITAL	Copperbelt	Kitwe
WUSAKILE MINE HOSPITAL	Copperbelt	Kitwe
73 INDEPENDENCE CLINIC- RAM	Copperbelt	Luanshya
ALLESSANDRAS URBAN HEALTH CENTRE	Copperbelt	Luanshya
CHAISA URBAN HEALTH CENTRE	Copperbelt	Luanshya
THOMSON DISTRICT HOSPITAL	Copperbelt	Luanshya
ROAN ANTELOPE GENERAL HOSPITAL	Copperbelt	Luanshya
MPATAMATU SECTION 25 MINI HOSPITAL	Copperbelt	Luanshya
LUFWANYAMA DISTRICT HOSPITAL	Copperbelt	Lufwanyama
ST MARYS FIRST LEVEL HOSPITAL	Copperbelt	Lufwanyama
MASAITI DISTRICT HOSPITAL	Copperbelt	Masaiti
MPONGWE MISSION HOSPITAL	Copperbelt	Mpongwe
ST THERESA MISSION HOSPITAL	Copperbelt	Mpongwe
KAMUCHANGA DISTRICT HOSPITAL	Copperbelt	Mufulira
MALCOM WATSON HOSPITAL	Copperbelt	Mufulira
RONALD ROSS GENERAL HOSPITAL	Copperbelt	Mufulira
ARTHUR DAVISON CHILDREN'S HOSPITAL	Copperbelt	Ndola
NDOLA TEACHING HOSPITAL	Copperbelt	Ndola
CHIFUBU 1ST LEVEL HOSPITAL	Copperbelt	Ndola
NORTHERN COMMAND MILITARY HOSPITAL	Copperbelt	Ndola
BWANUNKHA RURAL HEALTH CENTRE	Eastern	Chadiza
CHADIZA DISTRICT HOSPITAL	Eastern	Chadiza
CHAMA DISTRICT HOSPITAL	Eastern	Chama
CHASEFU MINI HOSPITAL	Eastern	Chasefu
CHIPATA CENTRAL HOSPITAL	Eastern	Chipata
CHIPATA DISTRICT HOSPITAL	Eastern	Chipata
MWAMI ADVENTIST HOSPITAL	Eastern	Chipata
ST. LUKES MISSION HOSPITAL-CHIPATA	Eastern	Chipata
KASENGA MINI HOSPITAL	Eastern	Chipangali
AFRICA KIDNEY CARE NETWORK DIALYSIS CENTRE	Eastern	Katete
ST. FRANCIS MISSION HOSPITAL	Eastern	Katete
LUMEZI MISSION HOSPITAL	Eastern	Lumezi
LUNDAZI DISTRICT HOSPITAL	Eastern	Lundazi
MAMBWE DISTRICT HOSPITAL	Eastern	Mambwe
KAMOTO MISSION HOSPITAL	Eastern	Mambwe
NYIMBA DISTRICT HOSPITAL	Eastern	Nyimba
KALINDAWALO GENERAL HOSPITAL	Eastern	Petauke
PETAUKE DISTRICT HOSPITAL	Eastern	Petauke
MIINGA MISSION HOSPITAL	Eastern	Petauke
NYANJE MISSION HOSPITAL	Eastern	Sinda
VUBWI DISTRICT HOSPITAL	Eastern	Vubwi
CHEMBE MINI-HOSPITAL	Luapula	Chembe
CHIENGE DISTRICT HOSPITAL	Luapula	Chienge
KASABA MISSION HOSPITAL (ST.MARGRET)	Luapula	Chifunabuli
LUBWE (ST JOSEPH) MISSION HOSPITAL	Luapula	Chifunabuli
KAWAMBWA DISTRICT HOSPITAL	Luapula	Kawambwa
MANSA GENERAL HOSPITAL	Luapula	Mansa
HOME OF COMPASSION HOSPITAL	Luapula	Mansa
MILENGE HOSPITAL	Luapula	Milenge
MBERESHI MISSION HOSPITAL	Luapula	Mwansabomb We
NG'ANGA BILONDA HOSPITAL	Luapula	Mwansabomb We
MWENSE DISTRICT HOSPITAL	Luapula	Mwense
MAMBILIMA MISSION HOSPITAL	Luapula	Mwense
NCHELENGE DISTRICT HOSPITAL	Luapula	Nchelenge
ST. PAULS MISSION HOSPITAL	Luapula	Nchelenge
SAMFYA DISTRICT HOSPITAL	Luapula	Samfya
ROYAL PALM HOSPITAL	Lusaka	Chilanga
RUTH KALULUMA MEMORIAL HOSPITAL	Lusaka	Chilanga
MT. EUGENIA RURAL HOSPITAL	Lusaka	Chilanga
CHONGWE DISTRICT HOSPITAL	Lusaka	Chongwe
NATIONAL HEART HOSPITAL	Lusaka	Chongwe
HALFWAYS FAMILY HOSPITAL	Lusaka	Chongwe
KATONDWE MISSION HOSPITAL	Lusaka	Luangwa
LUANGWA DISTRICT HOSPITAL	Lusaka	Luangwa
LEVY MWANAWASA TEACHING HOSPITAL	Lusaka	Lusaka
UNIVERSITY TEACHING HOSPITALS - ADULT HOSPITAL	Lusaka	Lusaka
UNIVERSITY TEACHING HOSPITALS -CHILDRENS HOSPITAL	Lusaka	Lusaka
UTH WOMEN AND NEWBORN HOSPITAL	Lusaka	Lusaka
CANCER DISEASES HOSPITAL	Lusaka	Lusaka
CHAINAMA HILLS COLLEGE HOSPITAL	Lusaka	Lusaka
CHAWAMA FIRST LEVEL HOSPITAL	Lusaka	Lusaka
CHILENJE FIRST LEVEL HOSPITAL	Lusaka	Lusaka
CHIPATA FIRST LEVEL HOSPITAL	Lusaka	Lusaka
KANYAMA FIRST LEVEL HOSPITAL	Lusaka	Lusaka
MATERO FIRST LEVEL HOSPITAL	Lusaka	Lusaka
BAULENI MINI HOSPITAL	Lusaka	Lusaka
MISISI MINI WOMEN AND NEWBORN HOSPITAL	Lusaka	Lusaka
VICTORIA HOSPITAL	Lusaka	Lusaka
FAIRVIEW HOSPITAL	Lusaka	Lusaka
COPTIC HOSPITAL	Lusaka	Lusaka
HILLTOP HOSPITAL	Lusaka	Lusaka
MEDLAND HOSPITAL	Lusaka	Lusaka
MAXCARE HOSPITAL	Lusaka	Lusaka
PEARL OF HEALTH HOSPITAL	Lusaka	Lusaka
PREMIUM MEDICAL SERVICES LTD HOSPITAL	Lusaka	Lusaka
ROYAL HOSPITAL	Lusaka	Lusaka
COMFORT HOSPITAL	Lusaka	Lusaka
EDEN UNIVERSITY HOSPITAL	Lusaka	Lusaka
WELLSPRING SPECIALITY HOSPITAL	Lusaka	Lusaka
VIVA MED HOSPITAL	Lusaka	Lusaka
ST LUKE'S MISSION HOSPITAL- MPANSHYA	Lusaka	Rufunsa
CHINSALI GENERAL HOSPITAL	Muchinga	Chinsali
CHINSALI DISTRICT HOSPITAL	Muchinga	Chinsali
ISOKA HOSPITAL	Muchinga	Isoka
MAFINGA DISTRICT HOSPITAL	Muchinga	Mafinga
MUYOMBE LEVEL 1 HOSPITAL	Muchinga	Mafinga
MICHAEL CHILUFYA SATA HOSPITAL	Muchinga	Mpika
MPIKA DISTRICT HOSPITAL	Muchinga	Mpika
CHILONGA MISSION HOSPITAL	Muchinga	Mpika
NAKONDE HOSPITAL	Muchinga	Nakonde
NAKONDE MINI HOSPITAL	Muchinga	Nakonde
CHILUBI ISLAND HOSPITAL	Northern	Chilubi
CHILUBI MAINLAND HOSPITAL	Northern	Chilubi
SANTA MARIA MISSION HOSPITAL	Northern	Chilubi
KAPUTA DISTRICT HOSPITAL	Northern	Kaputa
KASAMA GENERAL HOSPITAL	Northern	Kasama
ST. FIDELIS (CHILUBULA) MISSION HOSPITAL	Northern	Kasama
LUWINGU DISTRICT HOSPITAL	Northern	Luwingu
MBALA GENERAL HOSPITAL	Northern	Mbala
MPOROKOSO DISTRICT HOSPITAL	Northern	Mporokoso
MPULUNGU DISTRICT HOSPITAL	Northern	Mpulungu
SENGA HILL DISTRICT HOSPITAL	Northern	Sengahill
CHAVUMA DISTRICT HOSPITAL	North-Western	Chavuma
CHAVUMA MISSION HOSPITAL	North-Western	Chavuma
KALENE MISSION HOSPITAL	North-Western	Ikelenge
KABOMPO DISTRICT HOSPITAL	North-Western	Kabompo
LUMWANA DISTRICT HOSPITAL	North-Western	Kalumbila
TRIDENT HOSPITAL	North-Western	Kalumbila
MUKINGE MISSION HOSPITAL	North-Western	Kasempa
LOLOMA MISSION HOSPITAL	North-Western	Manyinga
MUFUMBWE DISTRICT HOSPITAL	North-Western	Mufumbwe
MWINILUNGA DISTRICT HOSPITAL	North-Western	Mwinilunga
SOLWEZI GENERAL HOSPITAL	North-Western	Solwezi
KANSANSHI MINE HOSPITAL	North-Western	Solwezi
CHITOKOLOKI MISSION HOSPITAL	North-Western	Zambezi
ZAMBEZI DISTRICT HOSPITAL	North-Western	Zambezi
CHIKANKATA MISSION HOSPITAL	Southern	Chikankata
KAFUE GORGE HOSPITAL	Southern	Chikankata
CHOMA GENERAL HOSPITAL	Southern	Choma
MACHA MISSION HOSPITAL	Southern	Choma
GWEMBE DISTRICT HOSPITAL	Southern	Gwembe
ITEZHI DISTRICT TEZHI HOSPITAL	Southern	Itezhi-Tezhi
KALOMO DISTRICT HOSPITAL	Southern	Kalomo
NAMWIANGA MISSION HOSPITAL	Southern	Kalomo
KAZUNGULA DISTRICT HOSPITAL	Southern	Kazungula
LIVINGSTONE TEACHING HOSPITAL	Southern	Livingstone
MAZABUKA GENERAL HOSPITAL	Southern	Mazabuka
ZAMBIA SUGAR HOSPITAL	Southern	Mazabuka
CHIKUNI MISSION HOSPITAL	Southern	Monze
MONZE MISSION HOSPITAL	Southern	Monze
NAMWALA HOSPITAL	Southern	Namwala
KASIYA MISSION HOSPITAL	Southern	Pemba
SIAVONGA DISTRICT HOSPITAL	Southern	Siavonga
MAAMBA GENERAL HOSPITAL	Southern	Sinazongwe
ZIMBA MISSION HOSPITAL	Southern	Zimba
KALABO HOSPITAL	Western	Kalabo
YUKA MISSION HOSPITAL	Western	Kalabo
KAOMA HOSPITAL	Western	Kaoma
MANGANGO MISSION HOSPITAL	Western	Kaoma
LEWANIKA GENERAL HOSPITAL	Western	Mongu
MONGU HOSPITAL	Western	Mongu
MULOBEZI RURAL HEALTH CENTRE	Western	Mulobezi
SICHILI MISSION HOSPITAL	Western	Mulobezi
MWANDI MISSION HOSPITAL	Western	Mwandi
NALOLO HOSPITAL	Western	Nalolo
SENANGA GENERAL HOSPITAL	Western	Senanga
YETA HOSPITAL	Western	Sesheke
SHANGOMBO HOSPITAL	Western	Shang'Ombo
LUKULU HOSPITAL	Western	Lukulu
LUAMPA MISSION HOSPITAL	Western	Luampa`;

function slugify(str) {
    return str.toLowerCase()
        .replace(/[^a-z0-9]+/g, '_')
        .replace(/^_|_$/g, '')
        .substring(0, 60);
}

function buildPayload() {
    const lines = RAW.trim().split('\n');
    const payload = {};
    const seen = {};

    for (const line of lines) {
        const parts = line.split('\t');
        if (parts.length < 3) continue;
        const name = parts[0].trim();
        const province = parts[1].trim();
        const district = parts[2].trim();
        if (!name) continue;

        // Derive a stable key from name + district to avoid collisions
        let key = slugify(name + '_' + district);
        if (seen[key]) {
            key = key + '_' + (seen[key]++);
        } else {
            seen[key] = 1;
        }

        payload[key] = { facility_name: name, province, district };
    }
    return payload;
}

async function main() {
    const payload = buildPayload();
    const count = Object.keys(payload).length;
    console.log(`Uploading ${count} facilities to Firebase…`);

    const response = await fetch(FIREBASE_URL, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
    });

    if (!response.ok) {
        const text = await response.text();
        console.error(`Firebase error ${response.status}: ${text}`);
        process.exit(1);
    }

    console.log(`Done. ${count} facilities written to Firebase RTDB.`);
}

main().catch(err => { console.error(err); process.exit(1); });
